name: 'unixify-action'
description: 'Convert Windows file paths to unix paths.'
branding:
  icon: 'folder'
  color: 'red'
inputs:
  path:
    description: 'windows path to convert'
    required: true
    default: '~/'
outputs:
  path:
    description: 'unix path'
runs:
  using: 'node16'
  main: 'index.js'